version: '3.7'

services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --ft_min_word_len=1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '23306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: